// <auto-generated />
using System;
using Infrastructure.Entity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815224153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Service.Entities.CatalogBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Book author");

                    b.Property<string>("AvailabilityStatus")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Current availability status");

                    b.Property<int?>("AvailableCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Number of available copies");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Book category or genre");

                    b.Property<string>("CoverColor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Cover color of the book");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Book description");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("International Standard Book Number");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int")
                        .HasComment("Year of publication");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Publisher name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Book title");

                    b.Property<int>("TotalCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Total number of copies");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Author")
                        .HasDatabaseName("IX_CatalogBook_Author");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_CatalogBook_Category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CatalogBook_CreatedAt");

                    b.HasIndex("Isbn")
                        .IsUnique()
                        .HasDatabaseName("UX_CatalogBook_Isbn");

                    b.HasIndex("Publisher")
                        .HasDatabaseName("IX_CatalogBook_Publisher");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_CatalogBook_Title");

                    b.HasIndex("Category", "Author")
                        .HasDatabaseName("IX_CatalogBook_Category_Author");

                    b.ToTable("CatalogBooks", null, t =>
                        {
                            t.HasComment("Catalog of books available in the system");

                            t.HasCheckConstraint("CK_CatalogBook_AvailableCopies_LessThanOrEqualTotal", "[AvailableCopies] <= [TotalCopies]");

                            t.HasCheckConstraint("CK_CatalogBook_AvailableCopies_NonNegative", "[AvailableCopies] >= 0");

                            t.HasCheckConstraint("CK_CatalogBook_PublicationYear_Valid", "[PublicationYear] IS NULL OR ([PublicationYear] >= 1000 AND [PublicationYear] <= YEAR(GETDATE()))");

                            t.HasCheckConstraint("CK_CatalogBook_TotalCopies_NonNegative", "[TotalCopies] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
